// import API_URLS from './APIUrls';

const australia = [
  {
    id: '1',
    ruName: 'Буйвол',
    latName: 'Bubalus arnee',
    description: 'Буйвол — парнокопытное млекопитающее из семейства полорогих. Один из самых крупных быков. Взрослые особи достигают длины более 3 метров. Высота в холке доходит до 2 м, а вес может достигать 1000 кг, в отдельных случаях до 1200, в среднем же взрослый самец весит около 900 кг. Рога доходят до 2 м, они направлены в стороны и назад и имеют полулунную форму и уплощённое сечение. У коров рога небольшие или отсутствуют.',
    img: 'https://national-travel.ru/wp-content/uploads/wtt-images/2019/01/avstraliyskiy-buyvol-599ee0e3ea8e0.jpg',
    audio: 'https://zvukipro.com/uploads/files/2019-12/1577123296_7df8c3540bc89f0.mp3',
    pressed: false,
  },
  {
    id: '2',
    ruName: 'Кенгуру',
    latName: 'Macropus',
    description: 'Кенгуру — общеупотребительное название группы животных из отряда двурезцовых сумчатых млекопитающих. В широком смысле термин кенгуру относится ко всем представителям семейства кенгуровых, особенно красного филандера, антилопового кенгуру, восточного серого (гигантского) кенгуру и западного серого кенгуру',
    img: 'https://dicktanty.ru/wp-content/uploads/2019/04/1422-624x468.jpg',
    audio: 'https://zvukipro.com/uploads/files/2020-01/1579104194_vyfu.mp3',
    pressed: false,
  },
  {
    id: '3',
    ruName: 'Коала',
    latName: 'Phascolarctos cinereus',
    description: 'Коа́ла — вид сумчатых, обитающий в Австралии. Единственный современный представитель семейства коаловых (Phascolarctidae) из отряда двурезцовых сумчатых (Diprotodontia).',
    img: 'https://s3.nat-geo.ru/images/2019/4/10/404e50588d5b4a079edd91d02c010ca3.max-1200x800.jpg',
    audio: 'https://zvukipro.com/uploads/files/2020-02/1581958703_koala_close_calls.mp3',
    pressed: false,
  },
  {
    id: '4',
    ruName: 'Мышь',
    latName: 'Muridae',
    description: 'Мыши́ные, или мы́ши — семейство млекопитающих из отряда грызунов (Rodentia). Длина тела от 5 см (мышь-малютка) до 48 см (южная тонкохвостая крыса Phloeomys cumingi).',
    img: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Apodemus_sylvaticus_bosmuis.jpg',
    audio: 'https://zvukipro.com/uploads/files/2017-08/1504172585_d097d0b2d183d0ba-d0bfd0b8d181d0bad0b0-d0bcd18bd188d0b8.mp3',
    pressed: false,
  },
  {
    id: '5',
    ruName: 'Тасманийский дьявол',
    latName: 'Sarcophilus harrisii',
    description: 'Тасманийский дьявол — млекопитающее семейства хищных сумчатых; единственный вид рода Sarcophilus. Его чёрная окраска, огромная пасть с острыми зубами, зловещие ночные крики и свирепый нрав дали основание прозвать этого коренастого хищника «дьяволом».',
    img: 'https://cs9.pikabu.ru/post_img/big/2018/03/22/4/1521697692189555456.jpg',
    audio: 'https://zvukipro.com/uploads/files/2020-01/1578068126_5a285fa29cc3fa5.mp3',
    pressed: false,
  },
  {
    id: '6',
    ruName: 'Лягушка',
    latName: 'Litoria',
    description: 'Австралийские квакши — род бесхвостых земноводных из семейства квакш, обитающих в Австралии и Океании.Общая длина представителей этого рода колеблется от 1,6 (Litoria microbelos) до 13,5 (Litoria infrafrenata) сантиметров.',
    img: 'https://animals-nn.ru/uploads/posts/2011-02/1296595927_greentreefrog_zoom.jpg',
    audio: 'https://zvukipro.com/uploads/files/2017-09/1504336916_zvuk-ljagushek-na-bolote.mp3',
    pressed: false,
  },
];

const europe = [
  {
    id: '1',
    ruName: 'Козел',
    latName: 'Capra',
    description: 'Го́рные козлы́, или просто козлы́ — род жвачных парнокопытных млекопитающих из подсемейства козлиных семейства полорогих. Некоторые виды этого рода называют козерогами, два вида, обитающих на Кавказе, — турами.Домашняя коза (Capra hircus) — одомашненный представитель этого рода, который произошёл от безоарового козла, в настоящее время выделяется в самостоятельный биологический вид. Доказано, что она одомашнена более 8500 лет назад.',
    img: 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Spanish_ibex.jpg',
    audio: 'https://zvukipro.com/uploads/files/2019-01/1548153619_hungry-goat_fk2w6we_.mp3',
    pressed: false,
  },
  {
    id: '2',
    ruName: 'Олень',
    latName: 'Cervus elaphus',
    description: 'Благоро́дный олень или настоящий олень — парнокопытное млекопитающее из семейства оленевых. Благородный олень обитает в большей части Европы, на Кавказе, в Малой Азии, Иране, в некоторых частях Западной и Центральной Азии. Он также обитает в регионе Атласских гор между Марокко и Тунисом на северо-западе Африки, являясь единственным видом оленей, обитающих в Африке.',
    img: 'https://belohota.by/images/animals/olen1.jpg',
    audio: 'https://zvukipro.com/uploads/files/2017-08/1504023558_sound_55.mp3',
    pressed: false,
  },
  {
    id: '3',
    ruName: 'Кролик',
    latName: 'Oryctolagus cuniculus',
    description: 'Дикий кролик или европейский кролик — вид кролика родом из южной Европы. Единственный вид кроликов, который был одомашнен и дал всё современное разнообразие пород. В течение истории кролики были случайно или нарочно завезены во многие изолированные экосистемы, включая Австралию, в которых они нарушали баланс, что часто приводило к экологическому бедствию. ',
    img: 'https://www.zooeco.com/Im13/krol.jpg',
    audio: 'https://zvukipro.com/uploads/files/2017-09/1506333670_zvuki-krolika.mp3',
    pressed: false,
  },
  {
    id: '4',
    ruName: 'Кабан',
    latName: 'Sus scrofa',
    description: 'Каба́н, или вепрь, или ди́кая свинья́ — млекопитающее из отряда парнокопытных, подотряда свинообразных (нежвачных), семейства свиней, рода кабанов. Является предком домашней свиньи.',
    img: 'https://o-prirode.ru/wp-content/uploads/2018/04/Dikiy-kaban-e1522763302461.jpg',
    audio: 'https://zvukipro.com/uploads/files/2018-10/1540547287_z_uki-zhi_otnyh-kaban.mp3',
    pressed: false,
  },
  {
    id: '5',
    ruName: 'Ежик',
    latName: 'Erinaceus europaeus',
    description: 'Обыкнове́нный ёж, или европе́йский ёж — вид млекопитающих из рода евразийских ежей семейства ежовых. Широко распространён в Европе, Малой Азии, Западной Сибири, северо-западе Казахстана, Амурской области, северном и северо-восточном Китае.',
    img: 'https://www.ptichka.ru/data/cache/2018feb/04/40/53561_18058.jpg',
    audio: 'https://zvukipro.com/uploads/files/2018-10/1540376425_z_uki-prirody-pyhtit.mp3',
    pressed: false,
  },
  {
    id: '6',
    ruName: 'Лиса',
    latName: 'Vulpes',
    description: 'Лиси́ца — общее название нескольких видов млекопитающих семейства псовые. Лишь 10 видов этой группы относят к роду собственно лисиц. Наиболее известный и распространённый представитель — обыкновенная лисица. Лисицы встречаются в фольклоре многих народов по всему миру.',
    img: 'https://1reg.by/wp-content/uploads/2020/02/lisa-ostanki1-21022020.jpg',
    audio: 'https://zvukipro.com/uploads/files/2018-10/1539110374_zvuki-izdavaemye-lisoj.mp3',
    pressed: false,
  },
];

const asia = [
  {
    id: '1',
    ruName: 'Слон',
    latName: 'Elephas maximus',
    description: 'Азиа́тский слон или индийский слон — млекопитающее отряда хоботных, единственный современный вид рода азиатских слонов и один из трёх современных видов семейства слоновых. Азиатский слон — второе по величине современное наземное животное после саванного слона.',
    img: 'https://vignette.wikia.nocookie.net/lisenot/images/8/86/%D0%90%D0%B7%D0%B8%D0%B0%D1%82%D1%81%D0%BA%D0%B8%D0%B9%28%D0%B8%D0%BD%D0%B4%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9%29_%D1%81%D0%BB%D0%BE%D0%BD.jpeg/revision/latest/scale-to-width-down/340?cb=20150521085352&path-prefix=ru',
    audio: 'https://zvukipro.com/uploads/files/2018-10/1540914137_zvuk-slona.mp3',
    pressed: false,
  },
  {
    id: '2',
    ruName: 'Тигр',
    latName: 'Panthera tigris',
    description: 'Тигр — вид хищных млекопитающих семейства кошачьих, один из четырёх представителей рода пантера, который относится к подсемейству больших кошек.Среди представителей этого вида встречаются крупнейшие животные семейства кошачьих. Тигр является одним из крупнейших наземных хищников, уступая по массе лишь белому и бурому медведям.',
    img: 'https://web-zoopark.ru/wp-content/uploads/2018/07/2-102.jpg',
    audio: 'https://zvukipro.com/uploads/files/2018-11/1541407341_tigr-tigr.mp3',
    pressed: false,
  },
  {
    id: '3',
    ruName: 'Лев',
    latName: 'Panthera leo persica',
    description: 'Азиа́тский лев — подвид льва, обитающий в Южной Азии. Впервые подробно описан в 1826 году австрийским зоологом Йоханном Н. Майером. Прежде был широко распространён на территории Южной Евразии от Греции до Индии. Бесконтрольная охота в эпоху Великих Моголов и британского владычества привела к тому, что к 1910 году в Британской Индии официально насчитывалось 13 львов-самцов. В 1955 году в получившей независимость Индии началась борьба за сохранение вида',
    img: 'https://savageworld.ru/images/animals/pantera-leo-persica-httpmetazoa-us.jpg',
    audio: 'https://zvukipro.com/uploads/files/2017-09/1504517379_lev-rychit.mp3',
    pressed: false,
  },
  {
    id: '4',
    ruName: 'Носорог',
    latName: 'Rhinoceros unicornis',
    description: 'Инди́йский носоро́г — самый крупный из азиатских носорогов. По размерам это второй в Азии зверь после слона. Другие названия (которые являются зачастую лишь калькой с названий зверя в других языках) — панцирный носорог, однорогий носорог. Латинское биноминальное наименование буквально означает «носорог однорогий».',
    img: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Indian_rhinoceros.png',
    audio: 'https://zvukipro.com/uploads/files/2019-10/1570454474_c2c3657e5f2f50a.mp3',
    pressed: false,
  },
  {
    id: '5',
    ruName: 'Сайга',
    latName: 'Saiga tatarica',
    description: 'Сайга́, маргач или сайга́к — парнокопытное млекопитающее из подсемейства настоящих антилоп (хотя из-за своеобразной анатомии его иногда вместе с тибетской антилопой относят к особому подсемейству Saiginae).',
    img: 'https://upload.wikimedia.org/wikipedia/commons/5/57/Saiga_antelope_at_the_Stepnoi_Sanctuary.jpg',
    audio: 'https://zvukipro.com/uploads/files/2020-02/1582272899_7897978hap987rk51nyjsa.mp3',
    pressed: false,
  },
  {
    id: '6',
    ruName: 'Крокодил',
    latName: 'Crocodylus porosus',
    description: 'Гребнистый крокодил — крупное современное пресмыкающееся, относящееся к семейству настоящих крокодилов отряда крокодилов. Наиболее крупный представитель своего отряда, а также самый большой наземный или прибрежный хищник. Самцы этого вида могут достигать длины семи метров при массе примерно до двух тонн; единственные современные крокодилы, регулярно вырастающие более 5,2 метров в длину.',
    img: 'https://m.polit.ru/media/photolib/2019/03/06/ps_10864652-3x2-940x627_1551870891.jpg',
    audio: 'https://zvukipro.com/uploads/files/2018-11/1541691216_z_uki-zhi_otnyh-ryk.mp3',
    pressed: false,
  },
];

const northAmerica = [
  {
    id: '1',
    ruName: 'Бурый медведь',
    latName: 'Ursus arctos',
    description: 'Бурый медведь - один из самых крупных и мощных наземных хищников Северной Америки. Эти медведи оснащены невтяжными когтями, которые используются в первую очередь для рытья, а также обеспечивают хорошее сцепление с поверхностью во время бега. Несмотря на массу тела, свыше 500 кг, эти животные развивают скорость до 50 км в час. Название животного говорит само за себя, бурые медведи имеют темно-коричневую или желтовато-коричневую шерсть.',
    img: 'https://vestikavkaza.ru/upload/2018-09-11/15366489675b976707a94435.87363534.jpg',
    audio: 'https://zvukipro.com/uploads/files/2018-10/1538581616_z_uki-zhi_otnyh-med_ed.mp3',
    pressed: false,
  },
  {
    id: '2',
    ruName: 'Журавль',
    latName: 'Grus grus',
    description: 'Звуки, издаваемые журавлем, похожи на звонкое «кур-лы – кур-лы». Журавли чаще всего поют дуэтом – одна птица начинает запев со слога «кур», а вторая подхватывает «лы». Если птица поёт одна, то она издает только звук «кур».',
    img: 'https://live.staticflickr.com/65535/49221158846_b0b69a58f1.jpg',
    audio: 'https://www.xeno-canto.org/sounds/uploaded/BLMSIUFTFU/XC512582-190604_1087_Grus_tok.mp3',
    pressed: false,
  },
  {
    id: '3',
    ruName: 'Лось',
    latName: 'Alces americanus',
    description: 'Лось американский - самый большой член семейства оленей. Тело американского лося тяжелое с длинными ногами и вытянутой мордой. Мех имеет темно-коричневый (почти черный) окрас. У самцов вырастают большие рога (самые крупные из живущих в наше время млекопитающих.',
    img: 'https://st.depositphotos.com/2808141/3391/i/450/depositphotos_33913915-stock-photo-moose.jpg',
    audio: 'https://zvukipro.com/uploads/files/2017-08/1504022348_sound_5.mp3',
    pressed: false,
  },
  {
    id: '4',
    ruName: 'Волк',
    latName: 'lupus tundrarum',
    description: 'Поля́рный волк - полярный волк обитает на обширных пространствах полярных регионов, зимой в условиях полярной ночи. Чтобы выжить, волк приспособился есть любой корм, который только попадается. Он хорошо приспособлен к жизни в Арктике: может годами жить при минусовой температуре, месяцами не видеть солнечного света и неделями оставаться без пищи..',
    img: 'https://imgtube.ru/images/stories/2013/02/512-polar-wolf/8.jpg',
    audio: 'https://zvukipro.com/uploads/files/2019-06/1559544471_wolf-howl-sound.mp3',
    pressed: false,
  },
  {
    id: '5',
    ruName: 'Хорек',
    latName: 'Mustela nigripes',
    description: 'Хорек - предыдущие представители североамериканской фауны в этом списке имеют относительно здоровые и процветающие популяции, но американский хорёк балансирует на грани исчезновения. На самом деле, эти член семейства куньих, в буквальном смысле умер и воскрес. Вид был объявлен вымершим в дикой природе в 1987 году, а затем был успешно восстановлен в Аризоне, Вайоминге и Южной Дакоте.',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Mustela_nigripes_2.jpg',
    audio: 'https://zvukipro.com/uploads/files/2020-04/1585736809_zvuk-horka.mp3',
    pressed: false,
  },
  {
    id: '6',
    ruName: 'Бобр',
    latName: 'Castor canadensis',
    description: 'Канадский бобр - полуводное млекопитающее имеет горизонтально сплюснутый и широкой, покрытый чешуёй хвост. Пальцы грызуна, расположенные на задних конечностях, соединены друг с другом особой плавательной перепонкой, благодаря чему такое животное является отличным пловцом.',
    img: 'https://simple-fauna.ru/wp-content/uploads/2019/02/zhivotnye-severnoj-ameriki-3.jpg',
    audio: 'https://zvukipro.com/uploads/files/2017-12/1513206542_urchanie-bobra.mp3',
    pressed: false,
  },
];

const southAmerica = [
  {
    id: '1',
    ruName: 'Выдра',
    latName: 'Lutra lutra',
    description: 'Выдра -  вид хищных млекопитающих из семейства куньих, ведущих полуводный образ жизни. В литературе под словом «выдра» обычно подразумевается именно этот вид, хотя в роде выдр несколько видов.',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/89/Loutre2.jpg',
    audio: 'https://zvukipro.com/uploads/files/2019-08/1566025964_8b5b89b221214aa.mp3',
    pressed: false,
  },
  {
    id: '2',
    ruName: 'Пума',
    latName: 'Puma concolor',
    description: 'Пу́ма  -  хищник рода Пумы семейства кошачьих. Обитает в Северной и Южной Америке. Самый крупный представитель рода пум. Длина тела животного составляет 100—180 см, при длине хвоста 60—75 см, высота в холке 61—76 см при весе до 105 кг (самцы). Охотится преимущественно на оленей.',
    img: 'https://lentachel.ru/netcat_files/Image/foto/2020/03/12/gornyy_lev.jpg',
    audio: 'https://zvukipro.com/uploads/files/2019-11/1573201418_8608ecc935ac7a5.mp3',
    pressed: false,
  },
  {
    id: '3',
    ruName: 'Гуана́ко',
    latName: 'Lama guanicoe',
    description: 'Гуана́ко  -  млекопитающее рода лам семейства верблюдовых. Является предком одомашненной ламы. Животное стройного, лёгкого телосложения, по пропорциям напоминающее оленя или антилопу, но с более вытянутой шеей. Длинная шея гуанако служит балансиром при ходьбе и беге. Длина тела 120—175 см, длина хвоста — 15-25 см, высота в холке 90-130 см; масса — 115—140 кг. Конечности двупалые, сохранились только третий и четвёртый пальцы.',
    img: 'https://www.zoo-ekzo.ru/sites/default/files/styles/large/public/lama_guanicoe.jpg?itok=NawK6vzq',
    audio: 'https://zvukipro.com/uploads/files/2019-10/1571469466_2ad4a8a8fb0b9a0.mp3',
    pressed: false,
  },
  {
    id: '4',
    ruName: 'Ягуар',
    latName: 'Panthera onca',
    description: 'Ягуа́р — вид хищных млекопитающих семейства кошачьих, один из четырёх представителей рода пантер, который относится к подсемейству больших кошек. Единственный представитель рода на территории Северной и Южной Америки. Третий по размеру в мире, и самый крупный в Новом свете представитель семейства кошачьих[2]. Ареал вида простирается от Мексики к югу до Парагвая и северной Аргентины.',
    img: 'https://kipmu.ru/wp-content/uploads/yaguar-1.jpg',
    audio: 'https://zvukipro.com/uploads/files/2020-02/1580723856_e0002b6ec622b90.mp3',
    pressed: false,
  },
  {
    id: '5',
    ruName: 'Крокодил',
    latName: 'Crocodylus intermedius',
    description: 'Оринокский крокодил — пресмыкающееся семейства настоящих крокодилов, обитает в бассейне реки Ориноко на севере Южной Америки. Это один из самых крупных видов крокодилов и самое крупное животное Южной Америки: длина взрослых самцов может достигать, по крайней мере, 5,2 м, а иногда даже больше. Имелись также сообщения о более чем семиметровых экземплярах, но они малодостоверны.',
    img: 'https://lh3.googleusercontent.com/proxy/Sy-8MDPaeDHyC7mtJ1WofsLOqORY08Mr3yZHGXN0Oq13EnRsLxDMslIvivx2GDCGxiV61kO6j-4qJG550I4Fcvd74nK2zFoyrcE',
    audio: 'https://zvukipro.com/uploads/files/2018-11/1541691216_z_uki-zhi_otnyh-ryk.mp3',
    pressed: false,
  },
  {
    id: '6',
    ruName: 'Черепаха',
    latName: 'Chelonoidis elephantopus',
    description: 'Слоновая черепаха или галапагосская черепаха — вид сухопутных черепах. Эндемик Галапагосских островов, вид, находящийся под угрозой исчезновения. Является крупнейшим из живущих в настоящее время сухопутных черепах и 10-м по весу среди всех живущих рептилий, достигая веса более 400 кг и длины более 1,8 метров. При продолжительности жизни в дикой природе более 100 лет.',
    img: 'https://ianimal.ru/wp-content/uploads/2011/06/galapagos06.jpg',
    audio: 'https://zvukipro.com/uploads/files/2019-01/1547467920_aos04534_tortoise_mating_call.mp3',
    pressed: false,
  },
];

const africa = [
  {
    id: '1',
    ruName: 'Крокодил',
    latName: 'Crocodylus niloticus',
    description: 'Ни́льский крокоди́л — крупное пресмыкающееся семейства настоящих крокодилов. Самый большой из трёх видов крокодилов, обитающих в Африке, и второй по величине в мире, после гребнистого крокодила. Занимает верхнее положение в водных и околоводных экосистемах Африки. Взрослые особи способны справляться с такими крупными и сильными зверями, как черный носорог, гиппопотам, жираф, африканский буйвол, канна и лев.',
    img: 'https://theanimalw.com/wp-content/uploads/2015/08/318.jpg',
    audio: 'https://zvukipro.com/uploads/files/2018-11/1541691216_z_uki-zhi_otnyh-ryk.mp3',
    pressed: false,
  },
  {
    id: '2',
    ruName: 'Слон',
    latName: 'Loxodonta',
    description: 'Африканский слон - род африканских млекопитающих отряда хоботных. Предположительно включает два современных вида: саванный слон (Loxodonta africana (L. Blumenbach, 1797)) и лесной слон (Loxodonta cyclotis (Paul Matschie, 1900)). Последние исследования ДНК африканских слонов дают возможность предполагать, что эти два вида рода Loxodonta образовались 1,9 и 6 миллионов лет назад.',
    img: 'https://xn----dtblihagxczul4i.xn--p1ai/wp-content/uploads/2019/11/gfHWIGD.jpeg',
    audio: 'https://zvukipro.com/uploads/files/2018-10/1540913446_z_uk-slona.mp3',
    pressed: false,
  },
  {
    id: '3',
    ruName: 'Буйвол',
    latName: 'Syncerus caffer',
    description: 'Африканский буйвол - вид быков, широко распространённый в Африке. Будучи типичным представителем подсемейства быков, африканский буйвол, однако, весьма своеобразен и выделяется в отдельный род Syncerus с единственным видом (это также единственный из подсемейства быков, обитающий в Африке).',
    img: 'https://o-prirode.ru/wp-content/uploads/2018/03/buyvol-africanskiy-e1522010443209.jpg',
    audio: 'https://zvukipro.com/uploads/files/2019-12/1577123296_7df8c3540bc89f0.mp3',
    pressed: false,
  },
  {
    id: '4',
    ruName: 'Страус',
    latName: 'Struthio',
    description: 'Африка́нский стра́ус - бескилевая нелетающая птица, единственный современный представитель семейства страусовых',
    img: 'https://zooclub.ru/attach/16000/16112.jpg',
    audio: 'http://zoohoz.ru/wp-content/uploads/2016/02/Straus.mp3',
    pressed: false,
  },
  {
    id: '5',
    ruName: 'Лев',
    latName: 'Panthera leo',
    description: 'Лев — вид хищных млекопитающих, один из четырёх представителей рода пантер, относящегося к подсемейству больших кошек в составе семейства кошачьих. Наряду с тигром — самая крупная из ныне живущих кошек, масса некоторых самцов может достигать 250 кг',
    img: 'https://cdn24.img.ria.ru/images/07e4/03/05/1568176942_36:0:1749:1285_1400x0_80_0_0_bc3f38e58c2370975ea4e8f5be98ec99.jpg',
    audio: 'https://zvukipro.com/uploads/files/2017-09/1504517217_ryk-lva.mp3',
    pressed: false,
  },
  {
    id: '6',
    ruName: 'Лемур',
    latName: 'Lemuriformes',
    description: 'Лемуры — удивительные приматы, которые встречаются только на острове Мадагаскар, на восточном побережье Южной Африки. В целом насчитывается 30 различных видов лемуров, и все они являются эндемичными для Мадагаскара.',
    img: 'https://web-zoopark.ru/wp-content/uploads/2018/07/2-126.jpg',
    audio: 'https://zvukipro.com/uploads/files/2018-12/1544768142_z_uki-lemuro_.mp3',
    pressed: false,
  },
];

const arrCategorys = [
  {
    id: '0',
    categoryNumber: 0,
    name: 'Австралия',
    birds: australia,
  },
  {
    id: '1',
    categoryNumber: 1,
    name: 'Европа',
    birds: europe,
  },
  {
    id: '2',
    categoryNumber: 2,
    name: 'Азия',
    birds: asia,
  },
  {
    id: '3',
    categoryNumber: 3,
    name: 'Северная Америка',
    birds: northAmerica,
  },
  {
    id: '4',
    categoryNumber: 4,
    name: 'Южная Америка',
    birds: southAmerica,
  },
  {
    id: '5',
    categoryNumber: 5,
    name: 'Африка',
    birds: africa,
  },
];

export default arrCategorys;
